import { LegalLayout, Section, P, UL, AllCaps, Callout } from "./LegalLayout";

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      effectiveDate="August 27, 2026"
      operator="Anchor Ledger, a sole proprietorship operated from Germany. [NOTE — no incorporated legal entity exists; a sole proprietorship means personal, unlimited liability for whoever operates the Platform, not a corporate shield. Separately, German law (Telemediengesetz/Impressumspflicht) generally requires commercial websites to disclose the operating natural person's real name and address, not only a trade name — this page does not currently do so and should be reviewed with counsel before mainnet.]"
    >
      <Section n={1} title="Acceptance of These Terms">
        <P>
          By creating an account, linking a wallet, or otherwise using the Anchor Ledger platform ("Anchor Ledger," "we," "us," or "the Platform"), you ("you," "User," or "Client") agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Platform.
        </P>
      </Section>

      <Section n={2} title="Description of Service">
        <P>
          Anchor Ledger is an algorithmic digital-asset trading platform that generates trading signals and, upon your authorization, executes trades on your behalf across supported blockchain networks (currently Solana, Ethereum, and Tron) using a delegated wallet execution model described in Section 6.
        </P>
        <Callout>
          <strong>Current mode of operation:</strong> Anchor Ledger currently operates in a simulated/paper-trading mode. Signals are generated from live market data, and gains and losses are calculated and settled as if trades were executed at real market prices, but no order is currently placed on any external exchange or trading venue. Real order execution against live venues is planned as a future stage of development, and Users will be notified when that transition occurs.
        </Callout>
        <P>
          Anchor Ledger does not custody your funds in the traditional sense — trading authority is granted directly on-chain, to a capped amount you set, and can be revoked by you at any time. Anchor Ledger is not a bank, broker-dealer, or custodian, and is not currently claiming licensure as any such regulated entity.
        </P>
      </Section>

      <Section n={3} title="Eligibility">
        <UL items={[
          "You must be at least 18 years old (or the age of majority in your jurisdiction, if higher).",
          "You must not be a resident of, or accessing the Platform from, a jurisdiction subject to comprehensive economic sanctions administered by the U.S. Treasury's Office of Foreign Assets Control (OFAC) or equivalent sanctions regimes. [This is an industry-standard baseline, not a full regulatory analysis — confirm with counsel before enforcement action, and revisit if Anchor Ledger later specifically targets additional jurisdictions.]",
          "You must not be listed on OFAC's Specially Designated Nationals list or an equivalent sanctions/restricted-party list.",
          "You are solely responsible for determining whether your use of the Platform complies with the laws applicable to you in your own jurisdiction. Anchor Ledger does not currently restrict access by region beyond the sanctions screening above.",
        ]}/>
      </Section>

      <Section n={4} title="Not Financial Advice">
        <P>
          Nothing on the Platform constitutes investment, financial, legal, or tax advice. Trading signals and automated trades are generated by an algorithmic model and do not reflect a recommendation suited to your individual circumstances. You should consult your own independent advisors before using the Platform.
        </P>
      </Section>

      <Section n={5} title="Risks of Digital Asset Trading">
        <Callout>
          <strong>Simulated trading, real settlement:</strong> Anchor Ledger currently operates in a simulated/paper-trading mode: signals are generated from live market data, and gains/losses are calculated and settled as if trades were executed at real market prices, but no order is currently placed on any external exchange or venue. Real order execution against live venues is planned as a future stage of development, and Users will be notified when that transition occurs. This does not mean the Platform carries no financial risk to you today — see Section 6 regarding delegated on-chain fund movement, which is real regardless of simulated trading status.
        </Callout>
        <P>You acknowledge and accept the following risks, among others inherent to digital asset trading:</P>
        <UL items={[
          "Digital assets are highly volatile and you may lose some or all of the funds you make available for trading.",
          "Blockchain transactions are generally irreversible; errors, including those caused by software bugs, cannot always be undone.",
          "Smart contracts and delegated-authority mechanisms carry inherent technical risk, including the possibility of bugs in Anchor Ledger's own systems or in third-party protocols it interacts with.",
          "Past performance of any signal or strategy is not indicative of future results.",
          "Anchor Ledger may currently be operating in a test/limited-release capacity on test networks or with limited real-fund exposure; the specific status of the Platform at any given time is published on the Platform's public architecture page (anchorledger.space/architecture) and reflected in-app, and updates when execution status changes.",
        ]}/>
        <P>
          You agree that you are using the Platform at your own risk and that Anchor Ledger's liability for any loss is limited as set out in Section 13.
        </P>
      </Section>

      <Section n={6} title="Delegated Trading Authority">
        <P>
          To use the Platform's automated trading features, you authorize a Anchor Ledger-controlled delegate address to execute trades on your behalf, up to a maximum cumulative amount that you set ("Approval Cap"). This authorization:
        </P>
        <UL items={[
          "Is granted by a transaction you sign yourself, using your own wallet — Anchor Ledger never has access to your wallet's private keys.",
          "Is limited to the Approval Cap you set, and does not permit withdrawal of funds beyond that amount.",
          "May be revoked by you at any time through the Platform, which submits an on-chain revocation transaction; revocation takes effect once that transaction is confirmed on the relevant network, not merely when requested.",
          "Does not make Anchor Ledger a custodian of your assets — your assets remain in your own wallet at all times, subject only to the delegated authority described above.",
        ]}/>
      </Section>

      <Section n={7} title="Identity Verification (KYC)">
        <P>
          Anchor Ledger applies a reasonable identity-verification process before enabling certain features. You agree to provide accurate, current information and supporting documentation as requested, and acknowledge that Anchor Ledger may approve, reject, or request additional information at its discretion. Anchor Ledger is not currently representing that this process satisfies the identity-verification requirements of any specific regulatory regime or license; it is a risk-management measure appropriate to the current scale and nature of the Platform, and may be revised as the Platform and its regulatory posture evolve.
        </P>
      </Section>

      <Section n={8} title="Account Security">
        <P>
          You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs through your account. Notify Anchor Ledger immediately of any unauthorized access. Anchor Ledger offers optional two-factor authentication and encourages its use.
        </P>
      </Section>

      <Section n={9} title="Fees">
        <P>
          Anchor Ledger does not currently charge a separate platform fee, subscription, or commission. Trades are subject to ordinary venue and network trading fees — currently modeled within the Platform's simulated-trading engine at standard industry rates (see Section 2), and reflecting actual venue fees once live order execution begins — which are a cost of trading itself, not additional revenue to Anchor Ledger. Anchor Ledger reserves the right to introduce platform fees in the future, with advance notice to Users before any fee applies to their account.
        </P>
      </Section>

      <Section n={10} title="Prohibited Uses">
        <P>
          You agree not to: use the Platform for any unlawful purpose; attempt to circumvent identity verification or the Approval Cap mechanism; interfere with or disrupt the Platform's infrastructure; reverse-engineer non-public parts of the Platform; or use the Platform on behalf of a third party without disclosure.
        </P>
      </Section>

      <Section n={11} title="Suspension and Termination">
        <P>
          Anchor Ledger may suspend or terminate your access to the Platform, with or without notice, if it reasonably believes you have violated these Terms, if required by law, or if necessary to protect the Platform or other Users. You may stop using the Platform and revoke delegated authority at any time. Termination does not affect your ownership of your own on-chain assets.
        </P>
      </Section>

      <Section n={12} title="Disclaimers of Warranties">
        <AllCaps>
          THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. ANCHOR LEDGER DOES NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY TRADING SIGNAL OR STRATEGY WILL BE PROFITABLE.
        </AllCaps>
      </Section>

      <Section n={13} title="Limitation of Liability">
        <AllCaps>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ANCHOR LEDGER AND ITS OPERATOR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF FUNDS, PROFITS, OR DATA, ARISING FROM YOUR USE OF THE PLATFORM, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ANCHOR LEDGER'S TOTAL AGGREGATE LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE PLATFORM IS LIMITED TO THE TOTAL FEES, IF ANY, YOU PAID TO ANCHOR LEDGER IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM. [Given Anchor Ledger charges no platform fees as of this draft (Section 9), this cap is currently at or near zero for most claims — confirm with counsel that this is the intended level of protection, particularly given the operator's personal, unlimited liability as a sole proprietorship.]
        </AllCaps>
        <AllCaps>
          THIS LIMITATION DOES NOT APPLY TO LIABILITY THAT CANNOT BE LIMITED OR EXCLUDED UNDER APPLICABLE LAW, INCLUDING LIABILITY FOR INTENT OR GROSS NEGLIGENCE, OR FOR INJURY TO LIFE, BODY, OR HEALTH.
        </AllCaps>
      </Section>

      <Section n={14} title="Indemnification">
        <P>
          You agree to indemnify and hold harmless Anchor Ledger, its operator, and their respective affiliates, officers, and agents from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the Platform, your violation of these Terms, or your violation of any applicable law.
        </P>
      </Section>

      <Section n={15} title="Dispute Resolution; Governing Law">
        <P>
          These Terms are governed by the laws of Germany, without regard to conflict-of-laws principles. Disputes will be brought in the courts of Frankfurt, Germany. [Because Anchor Ledger operates as a sole proprietorship based in Germany, this reflects the operator's home jurisdiction by default rather than a deliberately chosen venue — given the Platform is accessible internationally, and depending on your own location, mandatory consumer-protection law in your jurisdiction may still apply regardless of this clause. CONFIRM WITH COUNSEL, including whether an arbitration clause would be preferable to court jurisdiction.]
        </P>
      </Section>

      <Section n={16} title="Changes to These Terms">
        <P>
          Anchor Ledger may update these Terms from time to time. Material changes will be communicated to Users through the Platform or by email prior to taking effect. Continued use of the Platform after changes take effect constitutes acceptance.
        </P>
      </Section>

      <Section n={17} title="Contact">
        <P>
          Questions about these Terms may be directed to support@anchorledger.space.
        </P>
      </Section>
    </LegalLayout>
  );
}
