server {
    listen 80;
    server_name anchorledger.duckdns.org ;

    resolver 127.0.0.11 valid=10s;

    # ACME challenge only
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Proxy API
    location /api/ {
        set $upstream_api api:3000;
        proxy_pass http://$upstream_api$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Temporary root — return 200 so nginx starts cleanly
    location / {
        return 200 'Anchor Ledger bootstrapping...';
        add_header Content-Type text/plain;
    }
}
